/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirearmIdRouteImport } from './routes/firearm.$id'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirearmIdRoute = FirearmIdRouteImport.update({
  id: '/firearm/$id',
  path: '/firearm/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/legal': typeof LegalRoute
  '/manufacturers': typeof ManufacturersRoute
  '/timeline': typeof TimelineRoute
  '/viewer': typeof ViewerRoute
  '/firearm/$id': typeof FirearmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/legal': typeof LegalRoute
  '/manufacturers': typeof ManufacturersRoute
  '/timeline': typeof TimelineRoute
  '/viewer': typeof ViewerRoute
  '/firearm/$id': typeof FirearmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/legal': typeof LegalRoute
  '/manufacturers': typeof ManufacturersRoute
  '/timeline': typeof TimelineRoute
  '/viewer': typeof ViewerRoute
  '/firearm/$id': typeof FirearmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/compare'
    | '/countries'
    | '/encyclopedia'
    | '/legal'
    | '/manufacturers'
    | '/timeline'
    | '/viewer'
    | '/firearm/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/compare'
    | '/countries'
    | '/encyclopedia'
    | '/legal'
    | '/manufacturers'
    | '/timeline'
    | '/viewer'
    | '/firearm/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/categories'
    | '/compare'
    | '/countries'
    | '/encyclopedia'
    | '/legal'
    | '/manufacturers'
    | '/timeline'
    | '/viewer'
    | '/firearm/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  CountriesRoute: typeof CountriesRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  LegalRoute: typeof LegalRoute
  ManufacturersRoute: typeof ManufacturersRoute
  TimelineRoute: typeof TimelineRoute
  ViewerRoute: typeof ViewerRoute
  FirearmIdRoute: typeof FirearmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firearm/$id': {
      id: '/firearm/$id'
      path: '/firearm/$id'
      fullPath: '/firearm/$id'
      preLoaderRoute: typeof FirearmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  CountriesRoute: CountriesRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  LegalRoute: LegalRoute,
  ManufacturersRoute: ManufacturersRoute,
  TimelineRoute: TimelineRoute,
  ViewerRoute: ViewerRoute,
  FirearmIdRoute: FirearmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
